bff_configs:
- task_id: historical_prices
  url: https://investidor10.com.br/api/cotacoes/acao/chart
  id: ticker
  url_sufix: 3650/true/real  # 10 years reading
  destination_folder: investidor_10/ticker_prices
- task_id: historical_prices
  url: https://investidor10.com.br/api/cotacoes/acao/chart
  id: ticker
  url_sufix: 3650/true/real  # 10 years reading
  destination_folder: investidor_10/ticker_prices
- task_id: historical_prices
  url: https://investidor10.com.br/api/cotacoes/acao/chart
  id: ticker
  url_sufix: 3650/true/real  # 10 years reading
  destination_folder: investidor_10/ticker_prices


class TickerIds(Enum):
    TICKER = "ticker"
    TICKER_ID = "ticker_id"
    COMPANY_ID = "company_id"