bff-configs:
- destination_folder: ticker_prices
  url: https://investidor10.com.br/api/cotacoes/acao/chart
  id: ticker
  url_sufix: 3650/true/real  # 10 years reading
  script: scripts/investidor10/default_cleaning.py

- destination_folder: net_income
  url: https://investidor10.com.br/api/balancos/receitaliquida/chart/
  id: company_id 
  url_sufix: 3650/0
  script: scripts/investidor10/default_cleaning.py

- destination_folder: assets_liabilities
  url: https://investidor10.com.br/api/balancos/ativospassivos/chart
  id: company_id 
  url_sufix: /3650
  script: scripts/investidor10/default_cleaning.py

- destination_folder: dividends
  url: https://investidor10.com.br/api/dividendos/chart/
  id: ticker
  url_sufix: /3650/ano
  script: scripts/investidor10/default_cleaning.py

- destination_folder: dividend_yield
  url: https://investidor10.com.br/api/dividend-yield/chart/
  id: ticker
  url_sufix: /3650/ano
  script: scripts/investidor10/default_cleaning.py

- destination_folder: historic_kpis
  url: https://investidor10.com.br/api/historico-indicadores/
  id: ticker_id
  url_sufix: /10
  script: scripts/investidor10/historic_kpis_cleaning.py

- destination_folder: prices_profit
  url: https://investidor10.com.br/api/cotacao-lucro/
  id: ticker
  url_sufix: adjusted/
  script: scripts/investidor10/prices_profit_cleaning.py