name: Continuous Deployment

on:
  pull_request:

jobs:
  lint-sql:
    name: SQl-linter
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2      
      - name: Install SQLFluff
        run: "pip install sqlfluff==2.3.4"
      - name: Lint models
        run: "sqlfluff lint --format github-annotation --annotation-level failure --dialect bigquery ."
        
